# Generated by Django 5.1.1 on 2025-09-17 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='media/')),
                ('duration', models.PositiveIntegerField(default=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='playlists.playlist')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
