# Generated by Django 5.1.1 on 2025-09-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
